### PR TITLE
Rephrase strings and propertys. Fixes #127

### LINKED ISSUE #127: Phrasing in the settings
### Steps to reproduce
1. Go to settings

### Actual behaviour
There is an on/off button for these 2 settings:
Disable form autofill
Disable password picker
which is confusing because when the button is on, the feature is deactivated.

### Expected behaviour
Should be
Enable form autofill
Enable password picker

### PR DESCRIPTION
**Pull request by brantje**

### CODE REVIEW

File: js/ui/popup/controllers/setup.js [hunk 1]
```diff
@@ -47,8 +47,8 @@
                 refreshTime: 60,
                 default_vault: {},
                 master_password: '',
-                disableAutoFill: false,
-                disablePasswordPicker: false,
+                enableAutoFill: true,
+                enablePasswordPickerr: true,
```
Comment (dardelet) [inline js/ui/popup/controllers/setup.js]: Typo here is var name
