### PR TITLE
Fix issue 123

### LINKED ISSUE #123: Password picker is not removed when changing pages is done with javascript
### Steps to reproduce
1. Go to https://www.bountysource.com/signin 
2. Click on the icon to make the password picker appear
3. Click on the bounty source logo to go back to the home

### Expected behaviour
Password picker should be removed

### Actual behaviour
Password picker is not removed
screen shot 2017-07-17 at 23 26 18

### PR DESCRIPTION
**Pull request by dardelet**
fixes #123

### CODE REVIEW

File: js/background/inject/inject.js [hunk 1]
```diff
@@ -84,6 +98,16 @@ $j(document).ready(function () {
         $j('.passwordPickerIframe:not(:last)').remove();
     }
 
+    function onFormIconClick(e) {
+        e.preventDefault();
+        e.stopPropagation();
+        var offsetX = e.offsetX;
+        var offsetRight = ($j(this).width() - offsetX);
+        if (offsetRight < $j(this).height()) {
+            showPasswordPicker(form);
```
Comment (dardelet) [inline js/background/inject/inject.js]: I forgot that form is defined inside the createFormIcon scope

Comment (brantje) [inline js/background/inject/inject.js]: Yea scrutinizer caught that one too.

**Comment by dardelet** [comment]
It's ready for review now
